apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toyapp
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Spec
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/hangelucci/deployment-argocd.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: src  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: toyapp

  # Sync policy
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    
    automated: 
      selfHeal: true
      prune: true